### ISSUE TITLE
A mistake in the code?

### ISSUE THREAD

**Issue by hangong** [ZZPot/Color-transfer#1]
```
cvtColor(imgs, imgs_lab, CV_BGR2Lab);
cvtColor(imgt, imgt_lab, CV_BGR2Lab);
```

I don't think you should convert RGB to CIE LAB and compute the mean and std. As this is not the way it is described in the paper. I think the result will be different.

**Comment by ZZPot** [comment]
I didn't know that BGR2Lab is BGR to CIE lab. Will be fixed.

**Comment by ZZPot** [comment]
Fixed.
