### ISSUE TITLE
Getting the code to run.

### ISSUE THREAD

**Issue by TJCoding** [ZZPot/Color-transfer#4]
Here’s what I had to do to get this code to run.

Changed the first two lines to 

_#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>_

(..which may be a quirk of my set up)

Add 
_#include <stdio.h>_

Modify 

_Mat min_mat = Mat::Mat(_            to  _Mat min_mat = Mat(_   

It is a shame that there is some dead code which is inadequately differentiated, but otherwise this is a great effort.

Thanks

**Comment by ZZPot** [comment]
Code is kinda old, so OpenCV changed a little.

**Comment by TJCoding** [comment]
Note also that 
cv::calcCovarMatrix(imgs.reshape(1, imgs.cols * imgs.rows),  cov, means, CV_COVAR_ROWS  | CV_COVAR_NORMAL );

should read

cv::calcCovarMatrix(imgs.reshape(1, imgs.cols * imgs.rows),  cov, means, CV_COVAR_ROWS  | CV_COVAR_NORMAL | CV_COVAR_SCALE);

in order to accommodate the case where the source and target images differ in size.

**Comment by ZZPot** [comment]
This code kinda old. I have to review it and change a little bit.

**Comment by TJCoding** [comment]
I originally raised this because I encountered a few very minor issues and I wanted to make other people aware of them,  I think it is now time to close the issue.   The code is generally very good and it has been very useful to me.
